language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - travis_retry npm run test
  - travis_retry npm run test-travis-chrome
  # chrome test needs to run in separate, because of a bug in karma:
  # https://github.com/karma-runner/karma/issues/1656
  - npm run lint
