language: node_js

node_js:
  - "8"
  - "10"
  - "11"

services:
  - xvfb

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0

script:
  - travis_retry npm run test
  - travis_retry npm run test-travis-chrome
  # chrome test needs to run in separate, because of a bug in karma:
  # https://github.com/karma-runner/karma/issues/1656
  - npm run lint
