version: '2'
services:

   web:
      build: .
      ports:
      - "5000:5555"
      volumes:
      -  .:/web
      links:
       - db

   data:
      build: ./data
      links:
       - db

   db:
     image: mongo
     ports:
      - "4000:27017"
